import { ParamCurrentData, ParamData, ParamKey } from 'src/app/features/param/param.type';
import { ExponentNumber } from 'exponential-number';
import { environment } from 'src/environments/environment.dev';

export const PARAM_KEYS = {
  simpleMoneyMultiplier: 'simpleMoneyMultiplier',
  simpleMoneyMultiplierIncrement: 'simpleMoneyMultiplierIncrement',
  crystalShardsMoneyMultiplier: 'crystalShardsMoneyMultiplier',
  simpleMoneyPower: 'simpleMoneyPower',
  baseCrystalChance: 'baseCrystalChance',
  crystalChance: 'crystalChance',
  bonusCrystalChance: 'bonusCrystalChance',
  moneyCrystalChance: 'moneyCrystalChance',
  prestigePointsCoefficient: 'prestigePointsCoefficient',
  prestigeBorder: 'prestigeBorder',
  prestigeBorderGrowth: 'prestigeBorderGrowth',
  prestigeMoneyPower: 'prestigeMoneyPower',
  prestigeCrystalChance: 'prestigeCrystalChance',
  prestigeCrystalShardsMultiplier: 'prestigeCrystalShardsMultiplier',
  baseRubyChance: 'baseRubiesChance',
  bonusPrestigePointsMultiplier: 'bonusPrestigePointsMultiplier',
  moneyLogBase: 'moneyLogBase',
  moneyLogPower: 'moneyLogPower',
  crystalShardsLogBase: 'crystalShardsLogBase',
  crystalShardsLogPower: 'crystalShardsLogPower',
  prestigeLogBase: 'prestigeLogBase',
  prestigeLogPower: 'prestigeLogPower',
  rubyShardsLogBase: 'rubyShardsLogBase',
  rubyShardsLogPower: 'rubyShardsLogPower',
  rubyShardsMoneyMultiplier: 'rubyShardsMoneyMultiplier',

  crystalChanceRootBaseForCrystals: 'crystalChanceRootBaseForCrystals',
  rubyChanceRootBaseForRubies: 'rubyChanceRootBaseForRubies',
} as const;

export const PARAM_DATA: Record<ParamKey, ParamData> = {
  [PARAM_KEYS.simpleMoneyMultiplier]: {
    name: 'Simple multiplier',
    defaultValue: new ExponentNumber(0, 1),
    prefix: 'x',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.simpleMoneyMultiplierIncrement]: {
    name: 'Simple multiplier increment',
    defaultValue: new ExponentNumber(0, 1),
    prefix: 'x',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.crystalShardsMoneyMultiplier]: {
    name: 'Crystal multiplier',
    defaultValue: new ExponentNumber(0, 1),
    prefix: 'x',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.simpleMoneyPower]: {
    name: 'Simple power',
    defaultValue: new ExponentNumber(0, 0),
    prefix: '^',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.baseCrystalChance]: {
    name: 'Base crystal chance',
    defaultValue: new ExponentNumber(0, 0),
    prefix: '+',
    isPercent: true,
    isResetOnPrestige: false,
    isWithOne: false,
  },
  [PARAM_KEYS.crystalChance]: {
    name: 'Upgrade crystal chance',
    defaultValue: new ExponentNumber(0, 0),
    prefix: '+',
    isPercent: true,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.bonusCrystalChance]: {
    name: 'Bonus crystal chance',
    defaultValue: new ExponentNumber(0, 0),
    prefix: '+',
    isPercent: true,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.moneyCrystalChance]: {
    name: 'Money crystal chance',
    defaultValue: new ExponentNumber(0, 0),
    prefix: '+',
    isPercent: true,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.prestigePointsCoefficient]: {
    name: 'Prestige points coefficient',
    defaultValue: new ExponentNumber(0, 10),
    prefix: '',
    isPercent: false,
    isResetOnPrestige: false,
    isWithOne: false,
  },
  [PARAM_KEYS.prestigeBorder]: {
    name: 'Prestige border',
    defaultValue: new ExponentNumber(1, environment.isBorderlessPrestige ? 1 : 10),
    prefix: '',
    isPercent: false,
    isResetOnPrestige: false,
    isWithOne: false,
  },
  [PARAM_KEYS.prestigeBorderGrowth]: {
    name: 'Prestige border growth',
    defaultValue: new ExponentNumber(0, 1.1),
    prefix: '^',
    isPercent: false,
    isResetOnPrestige: false,
    isWithOne: false,
  },
  [PARAM_KEYS.prestigeMoneyPower]: {
    name: 'Prestige money power',
    defaultValue: new ExponentNumber(0, 0),
    prefix: '^',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.prestigeCrystalChance]: {
    name: 'Prestige crystal chance',
    defaultValue: new ExponentNumber(0, 0),
    prefix: '+',
    isPercent: true,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.prestigeCrystalShardsMultiplier]: {
    name: 'Prestige crystal multiplier',
    defaultValue: new ExponentNumber(0, 1),
    prefix: 'x',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.baseRubyChance]: {
    name: 'Base ruby chance',
    defaultValue: new ExponentNumber(0, 0),
    prefix: '+',
    isPercent: true,
    isResetOnPrestige: false,
    isWithOne: false,
  },
  [PARAM_KEYS.bonusPrestigePointsMultiplier]: {
    name: 'Bonus PP multiplier',
    defaultValue: new ExponentNumber(0, 0),
    prefix: 'x',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.moneyLogBase]: {
    name: 'Money log base',
    defaultValue: new ExponentNumber(0, 0),
    prefix: '',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: true,
  },
  [PARAM_KEYS.moneyLogPower]: {
    name: 'Money log power',
    defaultValue: new ExponentNumber(0, 1),
    prefix: '^',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.crystalShardsLogBase]: {
    name: 'Crystal shards log base',
    defaultValue: new ExponentNumber(0, 0),
    prefix: '',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: true,
  },
  [PARAM_KEYS.crystalShardsLogPower]: {
    name: 'Crystal shards log power',
    defaultValue: new ExponentNumber(0, 1),
    prefix: '^',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.prestigeLogBase]: {
    name: 'Prestige log base',
    defaultValue: new ExponentNumber(0, 0),
    prefix: '',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: true,
  },
  [PARAM_KEYS.prestigeLogPower]: {
    name: 'Prestige log power',
    defaultValue: new ExponentNumber(0, 1),
    prefix: '^',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.rubyShardsLogBase]: {
    name: 'Ruby shards log base',
    defaultValue: new ExponentNumber(0, 0),
    prefix: '',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: true,
  },
  [PARAM_KEYS.rubyShardsLogPower]: {
    name: 'Ruby shards log power',
    defaultValue: new ExponentNumber(0, 1),
    prefix: '^',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.crystalChanceRootBaseForCrystals]: {
    name: 'Crystal chance log base for crystal',
    defaultValue: new ExponentNumber(0, 1),
    prefix: '',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: true,
  },
  [PARAM_KEYS.rubyChanceRootBaseForRubies]: {
    name: 'Ruby chance log base for rubies',
    defaultValue: new ExponentNumber(0, 1),
    prefix: '',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: true,
  },
  [PARAM_KEYS.rubyShardsMoneyMultiplier]: {
    name: 'Ruby shards money multiplier',
    defaultValue: new ExponentNumber(0, 1),
    prefix: 'x',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: false,
  },
};

export const PARAM_CURRENT_VALUE: Record<ParamKey, ParamCurrentData> = {
  [PARAM_KEYS.simpleMoneyMultiplier]: {
    value: PARAM_DATA[PARAM_KEYS.simpleMoneyMultiplier].defaultValue.copy(),
  },
  [PARAM_KEYS.simpleMoneyMultiplierIncrement]: {
    value: PARAM_DATA[PARAM_KEYS.simpleMoneyMultiplierIncrement].defaultValue.copy(),
  },
  [PARAM_KEYS.crystalShardsMoneyMultiplier]: {
    value: PARAM_DATA[PARAM_KEYS.crystalShardsMoneyMultiplier].defaultValue.copy(),
  },
  [PARAM_KEYS.simpleMoneyPower]: {
    value: PARAM_DATA[PARAM_KEYS.simpleMoneyPower].defaultValue.copy(),
  },
  [PARAM_KEYS.baseCrystalChance]: {
    value: PARAM_DATA[PARAM_KEYS.baseCrystalChance].defaultValue.copy(),
  },
  [PARAM_KEYS.bonusCrystalChance]: {
    value: PARAM_DATA[PARAM_KEYS.bonusCrystalChance].defaultValue.copy(),
  },
  [PARAM_KEYS.moneyCrystalChance]: {
    value: PARAM_DATA[PARAM_KEYS.moneyCrystalChance].defaultValue.copy(),
  },
  [PARAM_KEYS.crystalChance]: { value: PARAM_DATA[PARAM_KEYS.crystalChance].defaultValue.copy() },
  [PARAM_KEYS.prestigePointsCoefficient]: {
    value: PARAM_DATA[PARAM_KEYS.prestigePointsCoefficient].defaultValue.copy(),
  },
  [PARAM_KEYS.prestigeBorder]: {
    value: PARAM_DATA[PARAM_KEYS.prestigeBorder].defaultValue.copy(),
  },
  [PARAM_KEYS.prestigeBorderGrowth]: {
    value: PARAM_DATA[PARAM_KEYS.prestigeBorderGrowth].defaultValue.copy(),
  },
  [PARAM_KEYS.prestigeMoneyPower]: {
    value: PARAM_DATA[PARAM_KEYS.prestigeMoneyPower].defaultValue.copy(),
  },
  [PARAM_KEYS.prestigeCrystalChance]: {
    value: PARAM_DATA[PARAM_KEYS.prestigeCrystalChance].defaultValue.copy(),
  },
  [PARAM_KEYS.prestigeCrystalShardsMultiplier]: {
    value: PARAM_DATA[PARAM_KEYS.prestigeCrystalShardsMultiplier].defaultValue.copy(),
  },
  [PARAM_KEYS.baseRubyChance]: {
    value: PARAM_DATA[PARAM_KEYS.baseRubyChance].defaultValue.copy(),
  },
  [PARAM_KEYS.bonusPrestigePointsMultiplier]: {
    value: PARAM_DATA[PARAM_KEYS.bonusPrestigePointsMultiplier].defaultValue.copy(),
  },
  [PARAM_KEYS.moneyLogBase]: {
    value: PARAM_DATA[PARAM_KEYS.moneyLogBase].defaultValue.copy(),
  },
  [PARAM_KEYS.moneyLogPower]: {
    value: PARAM_DATA[PARAM_KEYS.moneyLogPower].defaultValue.copy(),
  },
  [PARAM_KEYS.crystalShardsLogBase]: {
    value: PARAM_DATA[PARAM_KEYS.crystalShardsLogBase].defaultValue.copy(),
  },
  [PARAM_KEYS.crystalShardsLogPower]: {
    value: PARAM_DATA[PARAM_KEYS.crystalShardsLogPower].defaultValue.copy(),
  },
  [PARAM_KEYS.prestigeLogBase]: {
    value: PARAM_DATA[PARAM_KEYS.prestigeLogBase].defaultValue.copy(),
  },
  [PARAM_KEYS.prestigeLogPower]: {
    value: PARAM_DATA[PARAM_KEYS.prestigeLogPower].defaultValue.copy(),
  },
  [PARAM_KEYS.rubyShardsLogBase]: {
    value: PARAM_DATA[PARAM_KEYS.rubyShardsLogBase].defaultValue.copy(),
  },
  [PARAM_KEYS.rubyShardsLogPower]: {
    value: PARAM_DATA[PARAM_KEYS.rubyShardsLogPower].defaultValue.copy(),
  },
  [PARAM_KEYS.crystalChanceRootBaseForCrystals]: {
    value: PARAM_DATA[PARAM_KEYS.crystalChanceRootBaseForCrystals].defaultValue.copy(),
  },
  [PARAM_KEYS.rubyChanceRootBaseForRubies]: {
    value: PARAM_DATA[PARAM_KEYS.rubyChanceRootBaseForRubies].defaultValue.copy(),
  },
  [PARAM_KEYS.rubyShardsMoneyMultiplier]: {
    value: PARAM_DATA[PARAM_KEYS.rubyShardsMoneyMultiplier].defaultValue.copy(),
  },
};
