import { ParamCurrentData, ParamData, ParamKey } from 'src/app/features/param/param.type';
import { ExponentNumber } from 'exponential-number';

export const PARAM_KEYS = {
  simpleMoneyMultiplier: 'simpleMoneyMultiplier',
  simpleMoneyMultiplierIncrement: 'simpleMoneyMultiplierIncrement',
  crystalShardsMoneyMultiplier: 'crystalShardsMoneyMultiplier',
  simpleMoneyPower: 'simpleMoneyPower',
  baseCrystalChance: 'baseCrystalChance',
  crystalChance: 'crystalChance',
  bonusCrystalChance: 'bonusCrystalChance',
  moneyCrystalChance: 'moneyCrystalChance',
  prestigePointsCoefficient: 'prestigePointsCoefficient',
  prestigeBorder: 'prestigeBorder',
  prestigeBorderGrowth: 'prestigeBorderGrowth',
  prestigeMoneyPower: 'prestigeMoneyPower',
  prestigeCrystalChance: 'prestigeCrystalChance',
  prestigeCrystalShardsMultiplier: 'prestigeCrystalShardsMultiplier',
  baseRubyChance: 'baseRubiesChance',
  bonusPrestigePointsMultiplier: 'bonusPrestigePointsMultiplier',
  moneyLogBase: 'moneyLogBase',
  moneyLogPower: 'moneyLogPower',
  crystalShardsLogBase: 'crystalShardsLogBase',
  crystalShardsLogPower: 'crystalShardsLogPower',
  prestigeLogBase: 'prestigeLogBase',
  prestigeLogPower: 'prestigeLogPower',
  rubyShardsLogBase: 'rubyShardsLogBase',
  rubyShardsLogPower: 'rubyShardsLogPower',
  crystalChanceRootBaseForCrystals: 'crystalChanceRootBaseForCrystals',
  rubyChanceRootBaseForRubies: 'rubyChanceRootBaseForRubies',
  bonusMoneyMultiplier: 'bonusMoneyMultiplier',
  rubyChance: 'rubyChance',
  rubyShardsMoneyMultiplier: 'rubyShardsMoneyMultiplier',
  rubyShardsMoneyPower: 'rubyShardsMoneyPower',
  rubyShardsCrystalChance: 'rubyShardsCrystalChance',
  rubyPrestigeChance: 'rubyPrestigeChance',
  rubyBonusChance: 'rubyBonusChance',
} as const;

export const PARAM_DATA: Record<ParamKey, ParamData> = {
  [PARAM_KEYS.simpleMoneyMultiplier]: {
    name: 'Simple multiplier',
    defaultValue: new ExponentNumber(0, 1),
    prefix: 'x',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.simpleMoneyMultiplierIncrement]: {
    name: 'Simple multiplier increment',
    defaultValue: new ExponentNumber(0, 1),
    prefix: 'x',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.crystalShardsMoneyMultiplier]: {
    name: 'Crystal multiplier',
    defaultValue: new ExponentNumber(0, 1),
    prefix: 'x',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.simpleMoneyPower]: {
    name: 'Simple power',
    defaultValue: new ExponentNumber(0, 0),
    prefix: '^',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.baseCrystalChance]: {
    name: 'Base crystal chance',
    defaultValue: new ExponentNumber(0, 0),
    prefix: '+',
    isPercent: true,
    isResetOnPrestige: false,
    isWithOne: false,
  },
  [PARAM_KEYS.crystalChance]: {
    name: 'Upgrade crystal chance',
    defaultValue: new ExponentNumber(0, 0),
    prefix: '+',
    isPercent: true,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.bonusCrystalChance]: {
    name: 'Bonus crystal chance',
    defaultValue: new ExponentNumber(0, 0),
    prefix: '+',
    isPercent: true,
    isResetOnPrestige: false,
    isWithOne: false,
  },
  [PARAM_KEYS.moneyCrystalChance]: {
    name: 'Money crystal chance',
    defaultValue: new ExponentNumber(0, 0),
    prefix: '+',
    isPercent: true,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.prestigePointsCoefficient]: {
    name: 'Prestige points coefficient',
    defaultValue: new ExponentNumber(0, 10),
    prefix: '',
    isPercent: false,
    isResetOnPrestige: false,
    isWithOne: false,
  },
  [PARAM_KEYS.prestigeBorder]: {
    name: 'Prestige border',
    defaultValue: new ExponentNumber(1, 10),
    prefix: '',
    isPercent: false,
    isResetOnPrestige: false,
    isWithOne: false,
  },
  [PARAM_KEYS.prestigeBorderGrowth]: {
    name: 'Prestige border growth',
    defaultValue: new ExponentNumber(0, 1.1),
    prefix: '^',
    isPercent: false,
    isResetOnPrestige: false,
    isWithOne: false,
  },
  [PARAM_KEYS.prestigeMoneyPower]: {
    name: 'Prestige money power',
    defaultValue: new ExponentNumber(0, 0),
    prefix: '^',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.prestigeCrystalChance]: {
    name: 'Prestige crystal chance',
    defaultValue: new ExponentNumber(0, 0),
    prefix: '+',
    isPercent: true,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.prestigeCrystalShardsMultiplier]: {
    name: 'Prestige crystal multiplier',
    defaultValue: new ExponentNumber(0, 1),
    prefix: 'x',
    isPercent: false,
    isResetOnPrestige: false,
    isWithOne: false,
  },
  [PARAM_KEYS.baseRubyChance]: {
    name: 'Base ruby chance',
    defaultValue: new ExponentNumber(0, 0),
    prefix: '+',
    isPercent: true,
    isResetOnPrestige: false,
    isWithOne: false,
  },
  [PARAM_KEYS.bonusPrestigePointsMultiplier]: {
    name: 'Bonus PP multiplier',
    defaultValue: new ExponentNumber(0, 1),
    prefix: 'x',
    isPercent: false,
    isResetOnPrestige: false,
    isWithOne: false,
  },
  [PARAM_KEYS.moneyLogBase]: {
    name: 'Money log base',
    defaultValue: new ExponentNumber(0, 10),
    prefix: '',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: true,
  },
  [PARAM_KEYS.moneyLogPower]: {
    name: 'Money log power',
    defaultValue: new ExponentNumber(0, 1),
    prefix: '^',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.crystalShardsLogBase]: {
    name: 'Crystal shards log base',
    defaultValue: new ExponentNumber(0, 6),
    prefix: '',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: true,
  },
  [PARAM_KEYS.crystalShardsLogPower]: {
    name: 'Crystal shards log power',
    defaultValue: new ExponentNumber(0, 1.5),
    prefix: '^',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.prestigeLogBase]: {
    name: 'Prestige log base',
    defaultValue: new ExponentNumber(0, 4),
    prefix: '',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: true,
  },
  [PARAM_KEYS.prestigeLogPower]: {
    name: 'Prestige log power',
    defaultValue: new ExponentNumber(0, 1),
    prefix: '^',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.rubyShardsLogBase]: {
    name: 'Ruby shards log base',
    defaultValue: new ExponentNumber(0, 1),
    prefix: '',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: true,
  },
  [PARAM_KEYS.rubyShardsLogPower]: {
    name: 'Ruby shards log power',
    defaultValue: new ExponentNumber(0, 2),
    prefix: '^',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.crystalChanceRootBaseForCrystals]: {
    name: 'Crystal chance log base for crystal',
    defaultValue: new ExponentNumber(0, 1),
    prefix: '',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: true,
  },
  [PARAM_KEYS.rubyChanceRootBaseForRubies]: {
    name: 'Ruby chance log base for rubies',
    defaultValue: new ExponentNumber(0, 1),
    prefix: '',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: true,
  },
  [PARAM_KEYS.bonusMoneyMultiplier]: {
    name: 'Bonus money multiplier',
    defaultValue: new ExponentNumber(0, 1),
    prefix: 'x',
    isPercent: false,
    isResetOnPrestige: false,
    isWithOne: false,
  },
  [PARAM_KEYS.rubyChance]: {
    name: 'Ruby chance',
    defaultValue: new ExponentNumber(0, 0),
    prefix: '+',
    isPercent: true,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.rubyShardsMoneyMultiplier]: {
    name: 'Ruby shards money multiplier',
    defaultValue: new ExponentNumber(0, 1),
    prefix: 'x',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.rubyShardsMoneyPower]: {
    name: 'Ruby shards money power',
    defaultValue: new ExponentNumber(0, 0),
    prefix: '^',
    isPercent: false,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.rubyShardsCrystalChance]: {
    name: 'Ruby shards crystal chance',
    defaultValue: new ExponentNumber(0, 0),
    prefix: '+',
    isPercent: true,
    isResetOnPrestige: true,
    isWithOne: false,
  },
  [PARAM_KEYS.rubyBonusChance]: {
    name: 'Ruby bonus chance',
    defaultValue: new ExponentNumber(0, 0),
    prefix: '+',
    isPercent: true,
    isResetOnPrestige: false,
    isWithOne: false,
  },
  [PARAM_KEYS.rubyPrestigeChance]: {
    name: 'Ruby prestige chance',
    defaultValue: new ExponentNumber(0, 0),
    prefix: '+',
    isPercent: true,
    isResetOnPrestige: true,
    isWithOne: false,
  },
};

export const PARAM_CURRENT_VALUE: Record<ParamKey, ParamCurrentData> = {
  [PARAM_KEYS.simpleMoneyMultiplier]: {
    value: PARAM_DATA[PARAM_KEYS.simpleMoneyMultiplier].defaultValue,
  },
  [PARAM_KEYS.simpleMoneyMultiplierIncrement]: {
    value: PARAM_DATA[PARAM_KEYS.simpleMoneyMultiplierIncrement].defaultValue,
  },
  [PARAM_KEYS.crystalShardsMoneyMultiplier]: {
    value: PARAM_DATA[PARAM_KEYS.crystalShardsMoneyMultiplier].defaultValue,
  },
  [PARAM_KEYS.simpleMoneyPower]: {
    value: PARAM_DATA[PARAM_KEYS.simpleMoneyPower].defaultValue,
  },
  [PARAM_KEYS.baseCrystalChance]: {
    value: PARAM_DATA[PARAM_KEYS.baseCrystalChance].defaultValue,
  },
  [PARAM_KEYS.bonusCrystalChance]: {
    value: PARAM_DATA[PARAM_KEYS.bonusCrystalChance].defaultValue,
  },
  [PARAM_KEYS.moneyCrystalChance]: {
    value: PARAM_DATA[PARAM_KEYS.moneyCrystalChance].defaultValue,
  },
  [PARAM_KEYS.crystalChance]: { value: PARAM_DATA[PARAM_KEYS.crystalChance].defaultValue },
  [PARAM_KEYS.prestigePointsCoefficient]: {
    value: PARAM_DATA[PARAM_KEYS.prestigePointsCoefficient].defaultValue,
  },
  [PARAM_KEYS.prestigeBorder]: {
    value: PARAM_DATA[PARAM_KEYS.prestigeBorder].defaultValue,
  },
  [PARAM_KEYS.prestigeBorderGrowth]: {
    value: PARAM_DATA[PARAM_KEYS.prestigeBorderGrowth].defaultValue,
  },
  [PARAM_KEYS.prestigeMoneyPower]: {
    value: PARAM_DATA[PARAM_KEYS.prestigeMoneyPower].defaultValue,
  },
  [PARAM_KEYS.prestigeCrystalChance]: {
    value: PARAM_DATA[PARAM_KEYS.prestigeCrystalChance].defaultValue,
  },
  [PARAM_KEYS.prestigeCrystalShardsMultiplier]: {
    value: PARAM_DATA[PARAM_KEYS.prestigeCrystalShardsMultiplier].defaultValue,
  },
  [PARAM_KEYS.baseRubyChance]: {
    value: PARAM_DATA[PARAM_KEYS.baseRubyChance].defaultValue,
  },
  [PARAM_KEYS.bonusPrestigePointsMultiplier]: {
    value: PARAM_DATA[PARAM_KEYS.bonusPrestigePointsMultiplier].defaultValue,
  },
  [PARAM_KEYS.moneyLogBase]: {
    value: PARAM_DATA[PARAM_KEYS.moneyLogBase].defaultValue,
  },
  [PARAM_KEYS.moneyLogPower]: {
    value: PARAM_DATA[PARAM_KEYS.moneyLogPower].defaultValue,
  },
  [PARAM_KEYS.crystalShardsLogBase]: {
    value: PARAM_DATA[PARAM_KEYS.crystalShardsLogBase].defaultValue,
  },
  [PARAM_KEYS.crystalShardsLogPower]: {
    value: PARAM_DATA[PARAM_KEYS.crystalShardsLogPower].defaultValue,
  },
  [PARAM_KEYS.prestigeLogBase]: {
    value: PARAM_DATA[PARAM_KEYS.prestigeLogBase].defaultValue,
  },
  [PARAM_KEYS.prestigeLogPower]: {
    value: PARAM_DATA[PARAM_KEYS.prestigeLogPower].defaultValue,
  },
  [PARAM_KEYS.rubyShardsLogBase]: {
    value: PARAM_DATA[PARAM_KEYS.rubyShardsLogBase].defaultValue,
  },
  [PARAM_KEYS.rubyShardsLogPower]: {
    value: PARAM_DATA[PARAM_KEYS.rubyShardsLogPower].defaultValue,
  },
  [PARAM_KEYS.crystalChanceRootBaseForCrystals]: {
    value: PARAM_DATA[PARAM_KEYS.crystalChanceRootBaseForCrystals].defaultValue,
  },
  [PARAM_KEYS.rubyChanceRootBaseForRubies]: {
    value: PARAM_DATA[PARAM_KEYS.rubyChanceRootBaseForRubies].defaultValue,
  },
  [PARAM_KEYS.bonusMoneyMultiplier]: {
    value: PARAM_DATA[PARAM_KEYS.bonusMoneyMultiplier].defaultValue,
  },
  [PARAM_KEYS.rubyChance]: {
    value: PARAM_DATA[PARAM_KEYS.rubyChance].defaultValue,
  },
  [PARAM_KEYS.rubyShardsMoneyMultiplier]: {
    value: PARAM_DATA[PARAM_KEYS.rubyShardsMoneyMultiplier].defaultValue,
  },
  [PARAM_KEYS.rubyShardsMoneyPower]: {
    value: PARAM_DATA[PARAM_KEYS.rubyShardsMoneyPower].defaultValue,
  },
  [PARAM_KEYS.rubyShardsCrystalChance]: {
    value: PARAM_DATA[PARAM_KEYS.rubyShardsCrystalChance].defaultValue,
  },
  [PARAM_KEYS.rubyBonusChance]: {
    value: PARAM_DATA[PARAM_KEYS.rubyBonusChance].defaultValue,
  },
  [PARAM_KEYS.rubyPrestigeChance]: {
    value: PARAM_DATA[PARAM_KEYS.rubyPrestigeChance].defaultValue,
  },
};
